### ISSUE TITLE
Reuse Gutentags

### ISSUE THREAD

**Issue by weilbith** [KeitaNakamura/highlighter.nvim#1]
Cause there is no further _Vim_ documentation than the Readme, I've to ask this here as an issue. 
Is this plugin able to reuse already generated tags by _Gutentags_ for example?

**Comment by weilbith** [comment]
Any response? :)

**Comment by KeitaNakamura** [comment]
Sorry for late reply. The plugin doesn’t support Gutentags and I don’t have time to implement the feature now :(

**Comment by weilbith** [comment]
Okay. Bummer! I like the idea but generating tags twice is a no-go for me, sry.
